### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by AjeetRawat25** [ConnectyCube/connectycube-ios-samples#2]
Hi team we are facing an issue in the api 

 URL:https://api.connectycube.com/chat/Dialog
headers: {
    "Accept-Language" = "en;q=1";
    "CB-OS" = "iOS 14.0";
    "CB-SDK" = "iOS 1.7.0   ";
    "CB-Token" = ef34ba7aae8b2143f57d006ca03135a054000c21;
    "ConnectyCube-REST-API-Version" = "0.1.1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "User-Agent" = "Chat/1.0 (iPhone; iOS 14.0; Scale/2.00)";
}
parameters: {
    "occupants_ids" = 1783453;
    type = 3;
}
2020-10-05 23:22:41.449493+0530 Chat[15368:337831] [REST]: Response[4]
headers: {
    "Access-Control-Allow-Origin" = "*";
    "CB-Token-ExpirationDate" = "2020-10-05 19:51:09 UTC";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "ConnectyCube-REST-API-Version" = "0.1.1";
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 05 Oct 2020 17:52:41 GMT";
    Duration = "1.053339";
    Server = "nginx/1.16.1";
    "Set-Cookie" = "_mkra_ctxt=105e06e90bcfbcdef4e6f44951ac5a9c--403; path=/; max-age=5; HttpOnly; secure";
    Status = "403 Forbidden";
    "Strict-Transport-Security" = "max-age=31536000";
    "Transfer-Encoding" = Identity;
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "cee11a82-d1d4-4c6e-9d25-ce0bc98bd8a6";
    "X-Runtime" = "0.009860";
    "X-XSS-Protection" = "1; mode=block";
}
error: Request failed: forbidden (403)
reasons: {
    errors =     {
        base =         (
            "Forbidden. Need user."
        );
    };
}

**Comment by DaveLomber** [comment]
In order to perform any operations, 
you need to login as a user

Please check the API https://developers.connectycube.com/ios/authentication-and-users?id=upgrade-session-token-user-login
